"""Postgres connection factory and schema initialization."""

from typing import Any
from urllib.parse import parse_qsl, unquote, urlparse

import psycopg
from psycopg.rows import dict_row

ARABIC_ROLE_TERMS = ("مصنع", "مستورد", "موزع")


def _connection_kwargs(database_url: str) -> dict[str, Any]:
    parsed = urlparse(database_url)
    if parsed.scheme not in {"postgres", "postgresql"}:
        return {"conninfo": database_url}

    kwargs: dict[str, Any] = {
        "host": parsed.hostname,
        "port": parsed.port or 5432,
        "dbname": unquote(parsed.path.lstrip("/") or "postgres"),
        "user": unquote(parsed.username or ""),
        "password": unquote(parsed.password or ""),
    }
    for key, value in parse_qsl(parsed.query):
        if key in {"sslmode", "connect_timeout", "application_name"}:
            kwargs[key] = value
    return kwargs


def get_connection(database_url: str) -> Any:
    """Return a Postgres connection suitable for Supabase transaction poolers."""
    return psycopg.connect(
        **_connection_kwargs(database_url),
        row_factory=dict_row,
        autocommit=False,
        prepare_threshold=None,
    )


def init_db(conn: Any) -> None:
    """Create all scraper tables in Postgres if not present. Idempotent."""
    statements = [
        """
        CREATE TABLE IF NOT EXISTS categories (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            parent_slug TEXT,
            result_count INTEGER DEFAULT 0,
            href TEXT DEFAULT '',
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS brands (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            result_count INTEGER DEFAULT 0,
            href TEXT DEFAULT '',
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS keywords (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            href TEXT DEFAULT '',
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS locations (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            type TEXT NOT NULL CHECK(type IN ('city','area','district')),
            external_id TEXT DEFAULT '',
            parent_slug TEXT REFERENCES locations(slug),
            result_count INTEGER DEFAULT 0,
            scraped_at TEXT
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_locations_parent_slug
            ON locations(parent_slug)
        """,
        """
        CREATE TABLE IF NOT EXISTS businesses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_url TEXT UNIQUE NOT NULL,
            business_name TEXT DEFAULT '',
            business_name_ar TEXT DEFAULT '',
            category_slug TEXT,
            category_ar TEXT DEFAULT '',
            city_slug TEXT,
            governorate_ar TEXT DEFAULT '',
            phone TEXT DEFAULT '',
            email TEXT DEFAULT '',
            website TEXT DEFAULT '',
            facebook_url TEXT DEFAULT '',
            address TEXT DEFAULT '',
            address_ar TEXT DEFAULT '',
            raw_html_hash TEXT DEFAULT '',
            source_tier INTEGER DEFAULT 0,
            scraped_at TEXT
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_businesses_category
            ON businesses(category_slug, city_slug)
        """,
        """
        CREATE TABLE IF NOT EXISTS business_facets (
            source_url TEXT NOT NULL REFERENCES businesses(source_url),
            facet_type TEXT NOT NULL CHECK(
                facet_type IN ('category','brand','keyword','city','area','district')
            ),
            slug TEXT NOT NULL,
            name TEXT DEFAULT '',
            PRIMARY KEY (source_url, facet_type, slug)
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_business_facets_type_slug
            ON business_facets(facet_type, slug)
        """,
        """
        CREATE TABLE IF NOT EXISTS scrape_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            target_type TEXT NOT NULL DEFAULT 'category'
                CHECK(target_type IN ('category','brand','keyword')),
            target_slug TEXT NOT NULL DEFAULT '',
            category_slug TEXT NOT NULL,
            city_slug TEXT DEFAULT '',
            status TEXT NOT NULL CHECK(status IN ('pending','running','done','failed')),
            pages_scraped INTEGER DEFAULT 0,
            rows_written INTEGER DEFAULT 0,
            started_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            error TEXT DEFAULT '',
            UNIQUE(target_type, target_slug, city_slug)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS schema_meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
        """,
    ]
    with conn.cursor() as cur:
        for statement in statements:
            cur.execute(statement)
        for column in ("business_name_ar", "category_ar", "governorate_ar", "address_ar"):
            cur.execute(f"ALTER TABLE businesses ADD COLUMN IF NOT EXISTS {column} TEXT DEFAULT ''")
        for term in ARABIC_ROLE_TERMS:
            cur.execute(
                """INSERT INTO categories (slug, name, parent_slug, result_count, href, scraped_at)
                VALUES (%s, %s, '', 0, %s, '')
                ON CONFLICT (slug) DO NOTHING""",
                (term, term, f"/ar/keyword/{term}"),
            )
            cur.execute(
                """INSERT INTO keywords (slug, name, href, scraped_at)
                VALUES (%s, %s, %s, '')
                ON CONFLICT (slug) DO NOTHING""",
                (term, term, f"/ar/keyword/{term}"),
            )
    conn.commit()
