"""Postgres connection factory and schema initialization."""

from typing import Any

import psycopg
from psycopg.rows import dict_row


def get_connection(database_url: str) -> Any:
    """Return a Postgres connection suitable for Supabase transaction poolers."""
    return psycopg.connect(
        database_url,
        row_factory=dict_row,
        autocommit=False,
        prepare_threshold=None,
    )


def init_db(conn: Any) -> None:
    """Create all scraper tables in Postgres if not present. Idempotent."""
    statements = [
        """
        CREATE TABLE IF NOT EXISTS categories (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            parent_slug TEXT,
            result_count INTEGER DEFAULT 0,
            href TEXT DEFAULT '',
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS brands (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            result_count INTEGER DEFAULT 0,
            href TEXT DEFAULT '',
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS keywords (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            href TEXT DEFAULT '',
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS locations (
            slug TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            type TEXT NOT NULL CHECK(type IN ('city','area','district')),
            external_id TEXT DEFAULT '',
            parent_slug TEXT REFERENCES locations(slug),
            result_count INTEGER DEFAULT 0,
            scraped_at TEXT
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS businesses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_url TEXT UNIQUE NOT NULL,
            business_name TEXT DEFAULT '',
            category_slug TEXT,
            city_slug TEXT,
            phone TEXT DEFAULT '',
            email TEXT DEFAULT '',
            website TEXT DEFAULT '',
            facebook_url TEXT DEFAULT '',
            address TEXT DEFAULT '',
            raw_html_hash TEXT DEFAULT '',
            source_tier INTEGER DEFAULT 0,
            scraped_at TEXT
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_businesses_category
            ON businesses(category_slug, city_slug)
        """,
        """
        CREATE TABLE IF NOT EXISTS business_facets (
            source_url TEXT NOT NULL REFERENCES businesses(source_url),
            facet_type TEXT NOT NULL CHECK(
                facet_type IN ('category','brand','keyword','city','area','district')
            ),
            slug TEXT NOT NULL,
            name TEXT DEFAULT '',
            PRIMARY KEY (source_url, facet_type, slug)
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS idx_business_facets_type_slug
            ON business_facets(facet_type, slug)
        """,
        """
        CREATE TABLE IF NOT EXISTS scrape_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            target_type TEXT NOT NULL DEFAULT 'category'
                CHECK(target_type IN ('category','brand','keyword')),
            target_slug TEXT NOT NULL DEFAULT '',
            category_slug TEXT NOT NULL,
            city_slug TEXT DEFAULT '',
            status TEXT NOT NULL CHECK(status IN ('pending','running','done','failed')),
            pages_scraped INTEGER DEFAULT 0,
            rows_written INTEGER DEFAULT 0,
            started_at TIMESTAMPTZ,
            finished_at TIMESTAMPTZ,
            error TEXT DEFAULT '',
            UNIQUE(target_type, target_slug, city_slug)
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS schema_meta (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL
        )
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_scrape_jobs_target_city
        ON scrape_jobs(target_type, target_slug, city_slug)
        """,
    ]
    with conn.cursor() as cur:
        for statement in statements:
            cur.execute(statement)
    conn.commit()
