CREATE TABLE IF NOT EXISTS public.categories (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    parent_slug TEXT,
    result_count INTEGER DEFAULT 0,
    href TEXT DEFAULT '',
    scraped_at TEXT
);

CREATE TABLE IF NOT EXISTS public.brands (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    result_count INTEGER DEFAULT 0,
    href TEXT DEFAULT '',
    scraped_at TEXT
);

CREATE TABLE IF NOT EXISTS public.keywords (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    href TEXT DEFAULT '',
    scraped_at TEXT
);

CREATE TABLE IF NOT EXISTS public.locations (
    slug TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('city','area','district')),
    external_id TEXT DEFAULT '',
    parent_slug TEXT REFERENCES public.locations(slug),
    result_count INTEGER DEFAULT 0,
    scraped_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_locations_parent_slug
    ON public.locations(parent_slug);

CREATE TABLE IF NOT EXISTS public.businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url TEXT UNIQUE NOT NULL,
    business_name TEXT DEFAULT '',
    category_slug TEXT,
    city_slug TEXT,
    phone TEXT DEFAULT '',
    email TEXT DEFAULT '',
    website TEXT DEFAULT '',
    facebook_url TEXT DEFAULT '',
    address TEXT DEFAULT '',
    raw_html_hash TEXT DEFAULT '',
    source_tier INTEGER DEFAULT 0,
    scraped_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_businesses_category
    ON public.businesses(category_slug, city_slug);

CREATE TABLE IF NOT EXISTS public.business_facets (
    source_url TEXT NOT NULL REFERENCES public.businesses(source_url),
    facet_type TEXT NOT NULL CHECK(
        facet_type IN ('category','brand','keyword','city','area','district')
    ),
    slug TEXT NOT NULL,
    name TEXT DEFAULT '',
    PRIMARY KEY (source_url, facet_type, slug)
);

CREATE INDEX IF NOT EXISTS idx_business_facets_type_slug
    ON public.business_facets(facet_type, slug);

CREATE TABLE IF NOT EXISTS public.scrape_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type TEXT NOT NULL DEFAULT 'category'
        CHECK(target_type IN ('category','brand','keyword')),
    target_slug TEXT NOT NULL DEFAULT '',
    category_slug TEXT NOT NULL,
    city_slug TEXT DEFAULT '',
    status TEXT NOT NULL CHECK(status IN ('pending','running','done','failed')),
    pages_scraped INTEGER DEFAULT 0,
    rows_written INTEGER DEFAULT 0,
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    error TEXT DEFAULT '',
    UNIQUE(target_type, target_slug, city_slug)
);

CREATE TABLE IF NOT EXISTS public.schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keywords ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_facets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.scrape_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schema_meta ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.categories FROM anon, authenticated;
REVOKE ALL ON public.brands FROM anon, authenticated;
REVOKE ALL ON public.keywords FROM anon, authenticated;
REVOKE ALL ON public.locations FROM anon, authenticated;
REVOKE ALL ON public.businesses FROM anon, authenticated;
REVOKE ALL ON public.business_facets FROM anon, authenticated;
REVOKE ALL ON public.scrape_jobs FROM anon, authenticated;
REVOKE ALL ON public.schema_meta FROM anon, authenticated;
